### ISSUE TITLE
See the overview of products in a grid

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#15]
## User story
1. As a User
2. I need to see all the products/models and their pictures 
3. So that I can select my desired product/model

## Acceptance criteria
* I see all the products of the category that I have chosen in a grid
* Grid items have a picture and the name of the product
* Page has to be scrolable

**Comment by olyaee** [comment]
Since we have only one model for each product we are going to only show the products yet

<img width="749" alt="Screenshot 2021-05-03 at 20 44 51" src="https://user-images.githubusercontent.com/13171558/116918614-6bbf6a80-ac50-11eb-9034-729a85470153.png">


In the future, if there are more models we will implement a dropdown menu where user can choose the model
<img width="748" alt="Screenshot 2021-05-03 at 20 46 53" src="https://user-images.githubusercontent.com/13171558/116918830-b345f680-ac50-11eb-969a-58b4c16b7fbc.png">

**Comment by Waldleufer** [comment]
We could maybe use https://material-ui.com/components/grid-list/ to do so

**Comment by Waldleufer** [comment]
However I tend towards using https://material-ui.com/components/grid/ and the [/grid-list](https://material-ui.com/components/grid-list/) Since I already worked with those (especially the layout tags are quite familiar to me)

**Comment by Waldleufer** [comment]
Regarding #29:
Material-UI also provides a customizable Table (MIT Licenced)
https://material-ui.com/components/data-grid/

**Comment by IremToroslu** [comment]
Thanks for the info that you have provided. I thought we could use image card components. We could also use this one as well  https://material-ui.com/components/grid-list/. Lets have a look at them both. Thanks for exchanging info.

**Comment by IremToroslu** [comment]
for instance ,https://material-ui.com/components/cards/. We can also easily add the dropdown box there at the bottom
