### ISSUE TITLE
Navigate through different Categories and display the corresponding Products (and their Models) as a List (No real Data, only dummy list)

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#25]
## User story
1. As a user
2. I need to navigate hierarchically inside the catalog
3. So that I can find and select my desired product and model

## Acceptance criteria
* A hierarchical or collapse/expand (or any other way you find useful) type of navigation bar. For example: After clicking on products I see transformers, gas turbines, and... . then after clicking on the gas turbine I see different models of a gas turbine(model 1, model 2, ....)

**Comment by olyaee** [comment]
https://miro.com/app/board/o9J_lJCD9Xc=/
Link to the miro workspace

**Comment by Waldleufer** [comment]
@olyaee @MichaelScheiderer

Atm, we are working towards displaying a searchable list of all the available scenarios, so that the user can select one scenario (let's say the bike Production) and then change variables at the canvas (#28) there how they please.

I looked into SimaPro and I also figured that due to the big number of different library products, we will get the preconfigured scenarios from the SimaPro experts. (As of now there are 3800+ Library Products which are at first glance pretty much uncategorized) 

According to our Project Description:

> The scenarios are the basic setup.
> The calculations are the usage of different materials for the scenario.

> The scenarios and the calculations **are predefined** and provided through an existing cloud
service API. 
> \- [Project Description](https://drive.google.com/file/d/1JqIpZgRfYLMGwwDKRPqQqKTmURvqx-SK/view?usp=sharing)

-> Only two scenarios are predefined at the moment but we can safely assume that it is not our task to create new baseline scenarios. 
We are nevertheless able to create different scenarios when the user selects certain variables and wants to save his work. This can be done by creating a new scenario, with data like Scenario-Autor, ...

-----

# Clarification

According to The PDF that explains the API access in [this location](https://drive.google.com/file/d/1_p2b645TjBpjC7jzw3PKQlJRHY1AzRX8/view?usp=sharing), we assume the following in SimaPro API terminology.

- So what is actually requested in this issue (as far as we understood) is a browsable list of the **scenarios**, which can e.g. be a scenario for a bike production. Or a gas turbine production.

- A scenario then consists out of Products `[(Endproduct, Component1, Component2) e.g. Bike, Frame, Gears]` and these Products are represented through Library Products from the SimaPro API `[e.g. Endproduct Bike = Component1 + Component2; Frame (Aluminum + Electricity); Gears (Steel + Heat)]`
 
- The data may or may not contain different versions of the Components which could be selected by the user as **Variables**

```diff 
- Unclear please specify!
```

- ➡️ Our Users want to be able to browse all available scenarios. 
- ➡️ They want to be able to select one scenario for further inspection.
- (➡️ And they want to be able to create different sub-versions of those specific scenarios using different predefined Components == Variables) 
  > however, I am not quite sure about this last point!) 

> \- Martin W

**Comment by Waldleufer** [comment]
Hey @gandompm ! Today we figured out where to put the list of scenarios that are requested in #25. We can probably provide the unique scenario ID of the selected scenario, and you could then use that for #28 

Atm we are planning to display a searchable list of all the available scenarios, so that the user can select one scenario (lets say the bike Production scenario) and change variables (Different possible components like Aluminum Frame / Steel Frame /...) there how they please.

**Comment by olyaee** [comment]
The hierarchy should look like this:
only the first two nests are shown in the left navigation bar.`After clicking on Products all the products are going to be shown on the right-hand side.
<img width="876" alt="Screenshot 2021-05-01 at 22 56 36" src="https://user-images.githubusercontent.com/13171558/116794856-9da9c300-aad0-11eb-8e6d-1dd735d522b1.png">

**Comment by Waldleufer** [comment]
Maybe we could rename this Issue to: 
"Navigate **to** products and their models."
Or to be more precise
=> "Navigate through different Product Categories and display the corresponding Products (and their Models) as a List."

Because the user doesn't actually browse _through_ all the products, but he browses _through the categories_ to reach specific products.

**Comment by gandompm** [comment]
> Hey @gandompm ! Today we figured out where to put the list of scenarios that are requested in #25. We can probably provide the unique scenario ID of the selected scenario, and you could then use that for #28
> 
> Atm we are planning to display a searchable list of all the available scenarios, so that the user can select one scenario (lets say the bike Production scenario) and change variables (Different possible components like Aluminum Frame / Steel Frame /...) there how they please.

**Comment by gandompm** [comment]
> > Hey @gandompm ! Today we figured out where to put the list of scenarios that are requested in #25. We can probably provide the unique scenario ID of the selected scenario, and you could then use that for #28
> > Atm we are planning to display a searchable list of all the available scenarios, so that the user can select one scenario (lets say the bike Production scenario) and change variables (Different possible components like Aluminum Frame / Steel Frame /...) there how they please.

Hi, @MartinDuersch, 
good, then I can send the Id to the server for calculation? did you get which API is exactly responsible for this? I couldn't understand yet which API is used for which request. 
as far as I know, your issue this week is only to show a navigation bar with products and their models. and my issue is to provide a way for users to change the variables of the model.

**Comment by Waldleufer** [comment]
Hi @gandompm, I am Martin Wagner (@Waldleufer) not Martin Dürsch 😉

**Comment by ScoutAtlas** [comment]
https://www.siemens-energy.com/global/en/company/about.html

Generations, Transmission, Industrial Applications.

Those are _"Offerings"_, and they hopefully won't change for a while.

--> https://www.siemens-energy.com/global/en/offerings.html
