### ISSUE TITLE
Select a model and set canvas up

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#28]
## User story

1. As a user
2. I want to select a Model
3. so that I can get detailed information about its baseline scenario

## Acceptance criteria
- After I select a Model, a canvas is created and the baseline scenario including its name and variables are shown

**Comment by Waldleufer** [comment]
More detailed Information about this: https://drive.google.com/drive/folders/1kM26KP8FQcds-y65TCeRtY5hToOF1uW9

**Comment by Waldleufer** [comment]
Hi @gandompm,

may I suggest you move your component to 

https://github.com/amosproj/amos-ss2021-carbon-footprint/blob/a0b324c378880a28a2a6f5e092ac46c35f140812/frontend/src/routes/PrivateRoutes.js#L16-L27

Since your page should show up after the user selects his Project and Model? We are already linking to the Details Page after the Project+Model was selected.

You should be able to replace line 17-26 with
```js
<Route exact path={SLUGS.details} component={TheParhamComponentGoesHere} /> 
```
to do so.

If you need any help with that, ping me 😉

**Comment by Waldleufer** [comment]
Martin Wagner gefällt Ihre E-Mail
